export const vegetableDefinitions = {
  'water spinach': 'A semi-aquatic leafy green with hollow stems and tender leaves, widely cooked in Southeast Asia.',
  'vietnamese coriander': 'An aromatic herb with pointed leaves and a pungent, peppery flavour used fresh in Vietnamese dishes.',
  'fish mint': 'A heart-shaped, strongly scented herb with a flavour often used alongside seafood and in Vietnamese salads.',
  'perilla': 'An aromatic herb with serrated leaves and a warm, slightly minty flavour used as a Vietnamese garnish.',
  'culantro': 'A long-leaved aromatic herb with a strong coriander-like flavour used in soups, sauces, and garnishes.',
  'cilantro': 'A soft-stemmed herb with fresh, citrusy leaves commonly used as a garnish and seasoning.',
  'thai basil': 'A sweet, anise-scented basil with purple stems used fresh in Southeast Asian soups and stir-fries.',
  'spearmint': 'A cool, sweet-smelling mint with rounded leaves used fresh in salads, drinks, and Vietnamese dishes.',
  'cuban oregano': 'A thick-leaved, oregano-scented herb used fresh to season soups, meats, and sauces.',
  'vietnamese balm': 'A pungent leafy herb with a peppery, citrus-like aroma used fresh with Vietnamese food.',
  'garlic chives': 'Flat, grass-like leaves with a mild garlic flavour used in dumplings, soups, and stir-fries.',
  'rice paddy herb': 'A delicate aquatic herb with a citrusy aroma used in Vietnamese soups and fish dishes.',
  'pepper elder': 'A succulent leafy green with a mild peppery flavour eaten raw or lightly cooked.',
  'water mimosa': 'An aquatic vegetable with feathery leaves and crisp hollow stems used in soups and stir-fries.',
  'bitter herb': 'A regional leafy green with a pronounced bitter taste, usually blanched or cooked before eating.',
  'vegetable fern': 'Tender young fern fronds harvested before unfurling and cooked as a leafy green.',
  'katuk': 'A shrub vegetable whose small dark-green leaves are cooked in soups and stir-fries.',
  'malabar spinach': 'A tropical vine with thick, fleshy leaves and stems used like spinach in cooked dishes.',
  'jute mallow': 'A leafy green with mucilaginous leaves that thicken soups and stews when cooked.',
  'amaranth greens': 'Tender leaves of an amaranth plant eaten as a nutritious cooked green.',
  'sweet potato leaves': 'Tender leaves and shoots from a sweet-potato vine, commonly stir-fried or added to soups.',
  'cassava leaves': 'Young leaves of the cassava plant, prepared by thorough cooking before they are eaten.',
  'banana blossom': 'The purple, layered flower bud of a banana plant, sliced and used in salads and soups.',
  'lotus stem': 'The crisp, hollow stem of a lotus plant, eaten fresh, pickled, or cooked in salads and soups.',
  'lotus root': 'The round, crunchy underground part of a lotus plant, recognized by its pattern of holes.',
  'bamboo shoots': 'Young edible shoots harvested from bamboo and cooked after their bitter outer layers are removed.',
  'taro stem': 'The thick, pale stalk of a taro plant, peeled and cooked in soups and sour broths.',
  'taro': 'A starchy underground corm with brown skin and pale flesh that must be cooked before eating.',
  'water caltrop': 'A hard-shelled aquatic nut with a white, starchy interior eaten boiled or roasted.',
  'mustard greens': 'Peppery leaves from a mustard plant, commonly stir-fried, pickled, or added to soups.',
  'choy sum': 'A leafy Chinese vegetable with tender stems and small yellow flowers, usually stir-fried.',
  'bok choy': 'A small Chinese cabbage with crisp white stalks and dark green leaves.',
  'napa cabbage': 'A pale, tightly layered Chinese cabbage with tender leaves used in soups, stir-fries, and pickles.',
  'chinese broccoli': 'A leafy brassica with thick stems and small flower buds, often steamed or stir-fried.',
  'crown daisy': 'A leafy green with deeply divided leaves and a distinctive herbal aroma used in soups and hotpots.',
  'watercress': 'A peppery aquatic leafy green commonly eaten raw or added to soups and salads.',
  'cabbage': 'A round-headed leafy brassica with tightly packed leaves eaten raw, cooked, or fermented.',
  'cauliflower': 'A brassica whose compact white flower head is eaten steamed, stir-fried, or roasted.',
  'broccoli': 'A green brassica with branching stalks and edible flower buds.',
  'kohlrabi': 'A swollen, crisp stem vegetable with pale flesh and a mild cabbage-like flavour.',
  'daikon': 'A long, white radish with crisp flesh and a mildly peppery taste used raw or cooked.',
  'carrot': 'A tapered orange root with a sweet, crunchy texture eaten raw or cooked.',
  'beetroot': 'A round or tapered root with deep red flesh and a sweet, earthy flavour.',
  'cucumber': 'A cool, watery fruit with crisp flesh and a thin green skin commonly eaten raw or pickled.',
  'bitter melon': 'A ridged green fruit with a strongly bitter taste used in soups and stir-fries.',
  'sponge gourd': 'A long, ridged gourd with soft flesh that becomes tender when cooked.',
  'ridge gourd': 'A ridged green gourd with pale flesh commonly peeled and cooked in soups or stir-fries.',
  'winter melon': 'A large, pale-fleshed gourd with a waxy surface used in soups and braised dishes.',
  'bottle gourd': 'A light-green gourd with mild, watery flesh used in soups and stews.',
  'chayote': 'A pale-green, pear-shaped fruit with crisp flesh used as a vegetable in cooked dishes.',
  'chayote shoots': 'Tender young shoots and leaves from a chayote vine, usually stir-fried or boiled.',
  'pumpkin': 'A firm-fleshed orange squash with edible seeds used in soups, stews, and desserts.',
  'okra': 'A ridged green pod containing small seeds and a naturally thickening interior used in soups and stews.',
  'yardlong bean': 'A very long, slender bean pod eaten young and commonly stir-fried or boiled.',
  'green bean': 'A tender immature bean pod eaten whole, usually steamed, boiled, or stir-fried.',
  'bean sprouts': 'Crisp young shoots grown from germinated beans and eaten raw or cooked.',
  'soybean sprouts': 'Nutty, pale shoots grown from germinated soybeans and used in soups and stir-fries.',
  'green peas': 'Small, round immature seeds enclosed in green pods and eaten fresh or cooked.',
  'winged bean': 'A climbing legume whose four-edged green pods, seeds, and young shoots are edible.',
  'hyacinth bean': 'A climbing legume producing flat pods and beans that are eaten after cooking.',
  'lima bean': 'A broad, creamy-coloured bean with a soft texture eaten fresh or dried and cooked.',
  'eggplant': 'A smooth-skinned fruit with spongy flesh that is usually cooked as a savoury vegetable.',
  'tomato': 'A juicy, usually red fruit with soft flesh and seeds used raw, cooked, or made into sauces.',
  'green papaya': 'The firm, unripe stage of a papaya, shredded or cooked in salads and savoury dishes.',
  'green banana': 'An unripe banana with firm, starchy flesh used cooked rather than as a sweet fruit.',
  'young jackfruit': 'The firm, unripe flesh of a jackfruit used as a vegetable in curries, salads, and stews.',
  'shallot': 'A small bulb with layered purple or brown skin and a mild onion flavour used as an aromatic.',
  'chinese onion': 'A small, crisp bulb with a mild onion flavour commonly pickled or used as a seasoning.',
  'garlic': 'A segmented bulb made of pungent cloves used to flavour savoury dishes.',
  'ginger': 'A knobbly, aromatic rhizome with warm, peppery heat used fresh, dried, or pickled.',
  'turmeric': 'A bright yellow rhizome with earthy bitterness used as a spice and natural colouring.',
  'galangal': 'A firm, aromatic rhizome with a sharp citrusy flavour used in Southeast Asian cooking.',
  'lemongrass': 'A fibrous stalk with a fresh lemon aroma used to flavour soups, marinades, and curries.',
  'scallion': 'A slender onion with a small white base and hollow green leaves used fresh or cooked.',
  'chili pepper': 'A pungent fruit of the pepper plant that adds heat and flavour to savoury dishes.',
  "bird's eye chili": 'A small, intensely hot chili commonly used to add sharp heat to sauces and dishes.',
  'betel leaf': 'A glossy, heart-shaped aromatic leaf used as a wrapper or garnish in Southeast Asian food.',
  'lolot leaf': 'A peppery, heart-shaped leaf used to wrap meat and flavour grilled Vietnamese dishes.',
  'pumpkin flowers': 'The edible yellow blossoms of a pumpkin plant, often stuffed, fried, or cooked in soup.',
  'sesbania flowers': 'Small yellow flowers from a sesbania tree used as a seasonal vegetable in soups and salads.',
  'hummingbird tree flowers': 'Long, pale flowers from a hummingbird tree eaten as a seasonal vegetable in soups and stir-fries.',
  'water lily stems': 'Crisp hollow stalks from a water lily plant used raw, pickled, or cooked in salads.',
  'lotus leaves': 'Large round leaves from a lotus plant used to wrap food or add fragrance to steamed dishes.',
  'tonkin jasmine flowers': 'Fragrant star-shaped flowers from a climbing plant eaten as a seasonal vegetable or cooked in soup.',
  'straw mushroom': 'A small, rounded mushroom with a smooth grey-brown cap often used in Asian cooking.',
  'shiitake mushroom': 'A brown-capped mushroom with a firm texture and rich savoury flavour.',
  'wood ear mushroom': 'A dark, thin mushroom with a rubbery, crunchy texture commonly used in soups and stir-fries.',
  'oyster mushroom': 'A fan-shaped mushroom with a delicate texture and mild savoury flavour.',
  'king oyster mushroom': 'A large mushroom with a thick white stem and a small brown cap.',
  'enoki mushroom': 'A cluster of slender white mushrooms with tiny caps and a crisp texture.',
  'termite mushroom': 'A wild edible mushroom traditionally gathered near termite nests and used in regional dishes.',
  'dried lily flowers': 'Dried unopened lily buds that are rehydrated and cooked in soups or stir-fries.',
  'moon-leaf vegetable': 'A tender regional leafy green gathered for use in Vietnamese soups and cooked dishes.',
  'anise-scented herb': 'A fragrant regional herb with a sweet, anise-like aroma used fresh as a garnish or seasoning.',
  'garcinia leaves': 'Sour young leaves from a Garcinia tree used to add acidity and aroma to Vietnamese soups.',
  'lantana leaves': 'Young aromatic leaves of a Lantana shrub used as a regional cooked leafy green.',
  'wild cosmos': 'Tender leaves of a regional flowering plant gathered and cooked as a leafy vegetable.',
  'horsfieldia leaves': 'Young leaves from a Horsfieldia tree used as a regional edible green in Vietnamese cooking.',
  'acronychia leaves': 'Aromatic young leaves from an Acronychia tree used as a regional herb or leafy green.',
  'bignay leaves': 'Young leaves from a bignay tree used fresh or cooked as a regional Vietnamese green.',
  'premna leaves': 'Aromatic leaves from a Premna shrub used in Vietnamese soups, salads, and cooked dishes.',
  'creeping fig leaves': 'Tender young leaves from a creeping fig vine used as a regional cooked vegetable.',
  'syzygium leaves': 'Young aromatic leaves from a Syzygium tree used as a regional herb or cooked green.',
  'cynometra leaves': 'Tender young leaves from a Cynometra tree gathered and eaten as a regional green.',
  'climbing fern shoots': 'Tender unfurled shoots of a climbing fern harvested and cooked as a seasonal vegetable.',
  'barringtonia leaves': 'Young leaves from a Barringtonia tree used as a regional edible green in Vietnamese dishes.',
  'ambarella leaves': 'Young leaves from an ambarella tree used fresh or cooked for their sour, aromatic flavour.',
  'starfruit leaves': 'Young leaves from a starfruit tree used as a regional herb or cooked leafy green.',
  'young mango leaves': 'Tender new leaves from a mango tree eaten fresh or used to add a sour, resinous note.',
  'guava leaves': 'Young aromatic leaves from a guava tree used as a regional edible green or herbal ingredient.',
  'fig leaves': 'Young leaves from a fig tree used as a regional vegetable after cooking.',
  'longan leaves': 'Young leaves from a longan tree used as a regional aromatic green in Vietnamese cooking.',
  'black plum leaves': 'Young leaves from a black-plum tree used as a sour or aromatic regional green.',
  'young tamarind leaves': 'Tender tamarind leaves with a pleasantly sour flavour used fresh or cooked.',
  'polyscias leaves': 'Aromatic leaves from a Polyscias plant used as a Vietnamese herb or cooked green.',
  'bitter leaf': 'A strongly bitter green that is commonly blanched or cooked before eating.',
  'pennywort': 'A creeping herb with small round leaves eaten raw, blended into drinks, or added to salads.',
  'lettuce': 'A soft or crisp leafy plant commonly eaten raw in salads, wraps, and garnishes.',
  'spinach': 'A leafy green with tender leaves that can be eaten raw or cooked.',
  'celery': 'A crisp, strongly scented plant with edible stalks and leaves used in soups and stir-fries.',
  'water celery': 'A water-loving herb with hollow stems and celery-like leaves used in soups and salads.',
  'dill': 'A feathery herb with a fresh, slightly sweet aroma used to season fish, soups, and pickles.',
  'pandan leaves': 'Long, fragrant leaves used to perfume rice, desserts, drinks, and savoury dishes.',
  'ramie leaves': 'Young leaves from a fibrous ramie plant used as a regional cooked green.',
  'lime leaves': 'Aromatic leaves from a lime tree used to add citrus fragrance to soups, curries, and marinades.',
  'lemon basil': 'A basil variety with a pronounced lemon aroma used fresh in Vietnamese dishes and drinks.',
  'jicama': 'A large brown-skinned root with crisp, juicy, mildly sweet flesh often eaten raw.',
  'potato': 'A starchy underground tuber with thin skin and pale flesh cooked in many savoury dishes.',
  'sweet potato': 'A starchy root with naturally sweet flesh that may be orange, yellow, white, or purple.',
  'cassava root': 'A starchy, woody-skinned root that must be peeled and thoroughly cooked before eating.',
  'corn': 'A tall cereal crop producing edible kernels arranged on a cob and eaten fresh or cooked.',
  'baby corn': 'A small immature cob harvested before the kernels fully develop and eaten whole.',
  'asparagus': 'Tender green or white shoots with tightly closed tips eaten steamed, grilled, or stir-fried.',
  'water chestnut': 'A crisp aquatic corm with dark skin and white flesh used fresh or cooked.',
  'yam': 'A starchy underground tuber with rough skin and firm flesh that is eaten cooked.',
  'taro leaves': 'Large leaves from a taro plant that are cooked thoroughly and used in soups or rolls.',
  'gai choy': 'A broad, peppery mustard green with thick stalks used in stir-fries, soups, and pickles.',
  'thai eggplant': 'A small, round eggplant often green or pale in colour and used in curries and stir-fries.',
  'kale': 'A hardy leafy brassica with ruffled leaves and a slightly earthy flavour.',
  'zucchini': 'A tender summer squash with smooth green skin and pale flesh usually cooked as a vegetable.',
  'bell pepper': 'A large, hollow pepper with crisp flesh and little heat, available in several colours.',
  'sour soup leaf': 'A sour-tasting leaf used to give Vietnamese soups and hotpots a fresh acidic flavour.',
  'moringa leaves': 'Small nutritious leaflets from a moringa tree used fresh or cooked in soups and curries.',
  'purslane': 'A succulent leafy plant with crisp stems and a mildly sour, lemony taste.',
  'chinese celery': 'A slender, strongly aromatic celery variety with thin stalks and abundant leaves.',
  'red radish': 'A small round radish with red skin, crisp white flesh, and a peppery taste.',
  'banana': 'A curved tropical fruit with soft sweet flesh inside a yellow or green peel.',
  'coconut': 'A large tropical fruit with a hard shell, white flesh, and refreshing liquid inside.',
  'mango': 'A tropical stone fruit with fragrant juicy flesh surrounding a large flat stone.',
  'pomelo': 'A large citrus fruit with thick rind and firm, mildly sweet segments.',
  'orange': 'A round citrus fruit with juicy segmented flesh and a fragrant peel.',
  'mandarin': 'A small, easy-to-peel citrus fruit with sweet segments and a strong aroma.',
  'lime': 'A small green citrus fruit with sharply acidic juice used in drinks, sauces, and cooking.',
  'kumquat': 'A small oval citrus fruit whose thin sweet peel and sour flesh are often eaten together.',
  'watermelon': 'A large round fruit with a hard rind, juicy flesh, and black or pale seeds.',
  'pineapple': 'A spiky tropical fruit with firm, juicy, sweet-and-acidic flesh.',
  'dragon fruit': 'A brightly coloured cactus fruit with speckled flesh and a mild, refreshing flavour.',
  'papaya': 'A soft tropical fruit with orange flesh and a central cavity filled with black seeds.',
  'jackfruit': 'A very large tropical fruit containing fragrant yellow pods around a fibrous core.',
  'durian': 'A large, spiky tropical fruit with creamy flesh and a strong distinctive aroma.',
  'mangosteen': 'A round fruit with thick purple skin and soft white segments with a sweet-tart taste.',
  'rambutan': 'A small tropical fruit with soft spiny hairs outside and juicy translucent flesh inside.',
  'longan': 'A small round fruit with thin brown skin, translucent flesh, and a dark seed.',
  'lychee': 'A small rough-skinned fruit with fragrant translucent flesh and a single large seed.',
  'star apple': 'A round tropical fruit with purple or green skin and soft, milky sweet flesh.',
  'guava': 'A fragrant fruit with edible skin and flesh containing many small hard seeds.',
  'rose apple': 'A bell-shaped tropical fruit with crisp watery flesh and a light floral aroma.',
  'sapodilla': 'A brown-skinned tropical fruit with soft grainy flesh and a sweet caramel-like flavour.',
  'sugar apple': 'A knobbly tropical fruit made of sweet, creamy segments surrounding hard seeds.',
  'soursop': 'A large green fruit with soft white fibrous flesh and a sweet-tart flavour.',
  'avocado': 'A pear-shaped fruit with rich creamy flesh surrounding one large stone.',
  'passion fruit': 'A round fruit with a tough shell and aromatic, seedy pulp inside.',
  'tamarind': 'A brown pod containing sticky, sour-sweet pulp around several seeds.',
  'starfruit': 'A ridged yellow-green fruit that forms star-shaped slices when cut across.',
  'ambarella': 'A crisp tropical stone fruit with green or yellow skin and pleasantly sour flesh.',
  'jujube': 'A small oval fruit that changes from green and crisp to brown and chewy as it ripens.',
  'fig': 'A soft, pear-shaped fruit with thin skin and many tiny edible seeds inside.',
  'pomegranate': 'A round fruit with tough skin and many juicy jewel-like seeds inside.',
  'grape': 'A small round or oval fruit that grows in bunches and may be eaten fresh or dried.',
  'strawberry': 'A red heart-shaped fruit covered with tiny seeds and known for its sweet-tart flavour.',
  'mulberry': 'A small elongated berry that may be dark purple, red, or white when ripe.',
  'canistel': 'A yellow tropical fruit with dense, smooth flesh often compared with cooked egg yolk.',
  'langsat': 'A small round tropical fruit with thin yellow skin and translucent sweet-sour segments.',
  'breadfruit': 'A large green tropical fruit with starchy flesh that is usually cooked before eating.',
  'cashew apple': 'The swollen juicy fruit attached to a cashew nut, with a sweet, astringent flavour.',
  'gac fruit': 'A round, spiny tropical fruit with bright red pulp surrounding large seeds.',
  'toddy palm fruit': 'A soft, jelly-like fruit from a palmyra palm, usually eaten chilled or in desserts.',
  'plum': 'A smooth-skinned stone fruit with juicy flesh and one hard central stone.',
  'peach': 'A soft, fragrant stone fruit with fuzzy skin, juicy flesh, and one large stone.',
  'persimmon': 'An orange fruit with smooth skin and sweet flesh that may be firm or very soft when ripe.',
  'apricot': 'A small orange stone fruit with soft skin, fragrant flesh, and one large stone.',
  'honeydew melon': 'A round melon with smooth pale skin and sweet, juicy green or white flesh.',
  'cantaloupe': 'A ribbed melon with netted skin, orange flesh, and a sweet fragrant aroma.',
  'cocoa fruit': 'A ridged pod containing cocoa beans surrounded by sweet white pulp.',
  "buddha's hand citron": 'An unusual citrus fruit divided into finger-like sections with fragrant peel and little or no pulp.'
};

export function vegetableDefinition(word) {
  return vegetableDefinitions[word] || 'An edible plant, fruit, herb, or fungus used in Vietnamese cooking.';
}
